userdebug_or_eng_prop is wrongly mapped to build_prop in 33.0.cil file.
it is causing below CTS testcase failure.

android.security.SELinuxTargetSdkTest#testNoHiddenSystemProperties
junit.framework.ComparisonFailure: Hidden system properties may not be readable by apps expected:<[]> but was:<[0]>
at junit.framework.Assert.assertEquals(Assert.java:85)
at android.security.SELinuxTargetSdkTestBase.noHiddenSystemProperties(SELinuxTargetSdkTestBase.java:206)
at android.security.SELinuxTargetSdkTest.testNoHiddenSystemProperties(SELinuxTargetSdkTest.java:102)

@Buganizer: 278669182
@topic:Bug_Fixes

Change-Id: I8d0228ffa466eacfa48088e4fdce78f496b666cd