Update patch set 6
Patch Set 6: Presubmit-Verified-1

=== Finished presubmit run: L57700000068698329 ===

FAIL: Some checks failed. See below.


=== aosp-master/aosp_arm64-eng ===

PASS: Built aosp-master/aosp_arm64-eng/4051057 (ToT). See https://android-build.googleplex.com/builds/pending/P4389084/aosp_arm64-eng/latest


=== aosp-master/aosp_x86-eng ===

PASS: Built aosp-master/aosp_x86-eng/4051057 (ToT). See https://android-build.googleplex.com/builds/pending/P4389083/aosp_x86-eng/latest


=== git_master/bullhead-userdebug_fastbuild3a_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4051081 (\'ETIMEDOUT\' was not declared in this scope".). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4389082/bullhead-userdebug_fastbuild3a_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq

SKIPPED: Tests were skipped for git_master/bullhead-userdebug_fastbuild3a_linux/4051081 (ToT). Internal error: cannot find a successful build output for target bullhead-userdebug_fastbuild3a_linux


=== git_master/gce_x86_phone-userdebug_fastbuild3c_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4051081 (could not apply a8832da... SEPolicy: Changes for new stack dumping scheme.). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4389085/gce_x86_phone-userdebug_fastbuild3c_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq

CONFLICT: Your changes failed to cherry-pick against build 4051081 (could not apply a8832da... SEPolicy: Changes for new stack dumping scheme.). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4389087/test_suites_x86_64_fastbuild3d_linux/latest

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4051081 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4051081 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux

SKIPPED: Tests were skipped for git_master/gce_x86_phone-userdebug_fastbuild3c_linux/4051081 (ToT). Internal error: cannot find a successful build output for target gce_x86_phone-userdebug_fastbuild3c_linux


=== git_master/sailfish-userdebug_fastbuild3_linux ===

CONFLICT: Your changes failed to cherry-pick against build 4051081 (could not apply a8832da... SEPolicy: Changes for new stack dumping scheme.). See logs/git.log in https://android-build.googleplex.com/builds/pending/P4389086/sailfish-userdebug_fastbuild3_linux/latest. NOTE: This build has automerged changes. You may need to perform a manual  merge. See http://go/automerger-presubmit-faq. 
Note: This is a checkbuild (go/checkbuild). It will take longer and could uncover errors not found in other builds.


===

Have a question? Found a bug? http://go/treehugger-troubleshoot

Patch-set: 6
Tag: autogenerated:TreeHugger:Verify-Fail
Reviewer: Gerrit User 1062513 <1062513@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0
Label: Presubmit-Verified=-1